const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let rows=[], ticker='AAPL', active='trend', source='DEMO', analysis=null, priceChart=null, equityChart=null;
const avg=a=>a.reduce((s,v)=>s+v,0)/a.length;
const std=a=>{const m=avg(a);return Math.sqrt(avg(a.map(v=>(v-m)**2)))};
const sma=(r,n,i)=>i+1<n?null:avg(r.slice(i-n+1,i+1).map(x=>x.close));
const rsi=(r,n,i)=>{if(i<n)return null;let g=0,l=0;for(let j=i-n+1;j<=i;j++){const d=r[j].close-r[j-1].close;g+=Math.max(d,0);l+=Math.max(-d,0)}if(!l)return 100;return 100-100/(1+g/l)};
const atr=(r,n,i)=>{if(i<n)return null;const t=[];for(let j=i-n+1;j<=i;j++)t.push(Math.max(r[j].high-r[j].low,Math.abs(r[j].high-r[j-1].close),Math.abs(r[j].low-r[j-1].close)));return avg(t)};
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const pct=n=>`${n>=0?'+':''}${n.toFixed(2)}%`;
function indicators(r,i){const s20=sma(r,20,i),s50=sma(r,50,i),s200=sma(r,200,i),rv=rsi(r,14,i),av=atr(r,14,i);if([s20,s50,s200,rv,av].some(v=>v==null))return null;const c=r.slice(i-19,i+1).map(x=>x.close),d=std(c);return{s20,s50,s200,rsi:rv,atr:av,lower:s20-2*d,upper:s20+2*d}}
function analyze(r){const i=r.length-1,p=i-1,latest=r[i],v=indicators(r,i),pv=indicators(r,p);if(!v||!pv)throw Error('At least 201 valid trading days are required.');const prior=r.slice(i-20,i),resistance=Math.max(...prior.map(x=>x.high)),support=Math.min(...prior.map(x=>x.low)),volAvg=avg(prior.map(x=>x.volume||0));const trendSpread=Math.abs(v.s20-v.s50)/latest.close*100,longSpread=Math.abs(v.s50-v.s200)/latest.close*100,atrPct=v.atr/latest.close*100;const regime=trendSpread>.6&&longSpread>1.25?'TRENDING':atrPct>2.75?'VOLATILE':'RANGE-BOUND';
 const trendBuy=pv.s20<=pv.s50&&v.s20>v.s50&&latest.close>v.s200,trendSell=pv.s20>=pv.s50&&v.s20<v.s50&&latest.close<v.s200;const trendSignal=trendBuy?'BUY':trendSell?'SELL':v.s20>v.s50&&latest.close>v.s200?'HOLD':'WATCH';
 const prev=r[p],meanBuy=prev.close<pv.lower&&latest.close>v.lower&&v.rsi<42,meanSell=prev.close>pv.upper&&latest.close<v.upper&&v.rsi>58;const meanSignal=meanBuy?'BUY':meanSell?'SELL':v.rsi<35||v.rsi>65?'WATCH':'HOLD';
 const atrBuy=latest.close>resistance+.15*v.atr&&latest.volume>volAvg*1.15,atrSell=latest.close<support-.15*v.atr&&latest.volume>volAvg*1.15;const atrSignal=atrBuy?'BUY':atrSell?'SELL':Math.min(Math.abs(latest.close-resistance),Math.abs(latest.close-support))<v.atr?'WATCH':'HOLD';
 const strategies={trend:{id:'trend',name:'Trend Confirmation',subtitle:'20 / 50 / 200-day averages',signal:trendSignal,reason:trendBuy?'The 20-day average crossed above the 50-day average, and price is above the 200-day trend.':trendSell?'The 20-day average crossed below the 50-day average while price is below the 200-day trend.':`Price is ${latest.close>v.s200?'above':'below'} the 200-day average, but there is no new confirmed 20/50 crossover.`,metrics:[['SMA 20',v.s20,'money'],['SMA 50',v.s50,'money'],['SMA 200',v.s200,'money']]},mean:{id:'mean',name:'Bollinger + RSI Reversal',subtitle:'Range-market mean reversion',signal:meanSignal,reason:meanBuy?'Price moved back inside the lower Bollinger Band after an oversold stretch—a confirmed bullish re-entry.':meanSell?'Price moved back inside the upper Bollinger Band after an overbought stretch—a confirmed bearish re-entry.':`RSI is ${v.rsi.toFixed(1)} and price has not completed a Bollinger Band re-entry.`,metrics:[['RSI 14',v.rsi,'number'],['Lower band',v.lower,'money'],['Upper band',v.upper,'money']]},atr:{id:'atr',name:'ATR Breakout',subtitle:'Volatility + volume confirmation',signal:atrSignal,reason:atrBuy?'Price cleared prior resistance plus an ATR buffer on stronger-than-normal volume.':atrSell?'Price broke prior support minus an ATR buffer on stronger-than-normal volume.':`A confirmed move requires a close above ${(resistance+.15*v.atr).toFixed(2)} or below ${(support-.15*v.atr).toFixed(2)}, plus volume confirmation.`,metrics:[['ATR 14',v.atr,'money'],['Resistance',resistance,'money'],['Volume vs avg',latest.volume/volAvg,'multiple']]}};
 const weights=regime==='TRENDING'?{trend:2,mean:.5,atr:1}:regime==='VOLATILE'?{trend:1,mean:.5,atr:2}:{trend:.75,mean:2,atr:.75};let score=0;Object.values(strategies).forEach(s=>score+=(s.signal==='BUY'?1:s.signal==='SELL'?-1:0)*weights[s.id]);const combined=score>=1.75?'BUY':score<=-1.75?'SELL':Math.abs(score)>.25?'WATCH':'HOLD';return{latest,...v,resistance,support,volAvg,regime,combined,score,strategies}}
function signalAt(r,i,id){try{return analyze(r.slice(0,i+1)).strategies[id].signal}catch{return'HOLD'}}
function backtest(r,id){let cash=1,shares=0,entry=0,trades=0,wins=0,peak=1,maxDD=0;const curve=[],start=200,startPrice=r[start+1]?.open||r[start].close;for(let i=start;i<r.length-1;i++){const signal=signalAt(r,i,id),next=r[i+1];if(!shares&&signal==='BUY'){shares=cash/next.open;entry=next.open;cash=0;trades++}else if(shares&&signal==='SELL'){cash=shares*next.open;if(next.open>entry)wins++;shares=0}const value=shares?shares*next.close:cash,hold=next.close/startPrice;peak=Math.max(peak,value);maxDD=Math.max(maxDD,(peak-value)/peak);if(i%5===0||i===r.length-2)curve.push({date:next.date,strategy:value,hold})}const final=shares?shares*r.at(-1).close:cash;if(shares&&r.at(-1).close>entry)wins++;return{returnPct:(final-1)*100,holdPct:(r.at(-1).close/startPrice-1)*100,trades,winRate:trades?wins/trades*100:0,maxDD:maxDD*100,curve}}
function demoRows(sym){let price=90+(sym.charCodeAt(0)||65)%35,seed=[...sym].reduce((s,c)=>s+c.charCodeAt(0),0)||42,out=[],day=new Date();while(out.length<520){day=new Date(day.getTime()-86400000);if(day.getDay()===0||day.getDay()===6)continue;seed=(seed*9301+49297)%233280;const n=seed/233280-.48,i=519-out.length,change=.00035+n*.022+Math.sin(i/27)*.0035,close=price,spread=close*(.005+Math.abs(n)*.012),open=close/(1+change);price=open;out.push({date:day.toISOString().slice(0,10),open,high:Math.max(open,close)+spread,low:Math.min(open,close)-spread,close,volume:Math.round(1e7*(.7+Math.abs(n)*1.6))})}return out.reverse()}
async function fetchMarket(sym){const url=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(sym)}?range=2y&interval=1d&events=div%2Csplits`;const res=await fetch(url);if(!res.ok)throw Error(`market service returned ${res.status}`);const body=await res.json(),x=body?.chart?.result?.[0];if(!x)throw Error(body?.chart?.error?.description||'ticker not found');const q=x.indicators?.quote?.[0],adj=x.indicators?.adjclose?.[0]?.adjclose||q.close;const data=x.timestamp.map((t,i)=>({date:new Date(t*1000).toISOString().slice(0,10),open:q.open[i],high:q.high[i],low:q.low[i],close:adj[i],volume:q.volume[i]})).filter(v=>[v.open,v.high,v.low,v.close].every(Number.isFinite));if(data.length<220)throw Error('not enough price history');return data}
async function scan(sym){sym=sym.toUpperCase().trim().replace(/[^A-Z.\-]/g,'').slice(0,10);if(!sym)return;const btn=$('#scanButton');btn.disabled=true;btn.textContent='Scanning…';let message;try{rows=await fetchMarket(sym);source='LIVE';message=`Live market data loaded for ${sym}. Quotes may be delayed.`}catch(e){rows=demoRows(sym);source='DEMO';message=`Live market data unavailable (${e.message}). Showing clearly labeled simulated data—do not use it for trading decisions.`}ticker=sym;analysis=analyze(rows);setSource(message);render();btn.disabled=false;btn.textContent='Run scan →'}
function setSource(message){const badge=$('#dataBadge'),notice=$('#notice');badge.className=`data-badge ${source.toLowerCase()}`;badge.querySelector('span').textContent=`${source} DATA`;notice.className=`notice show ${source.toLowerCase()}`;notice.textContent=message;$('#footerSource').textContent=source==='LIVE'?'Market data is supplied by Yahoo Finance and may be delayed.':'Demo data is simulated and not suitable for trading decisions.'}
function colorClass(el,signal){el.className=signal.toLowerCase();el.textContent=signal}
function render(){const a=analysis,s=a.strategies[active];$('#ticker').textContent=$('#heroTicker').textContent=ticker;$('#price').textContent=money(a.latest.close);$('#asOf').textContent=`As of ${a.latest.date}`;$('#regime').textContent=$('#heroRegime').textContent=a.regime;$('#regimeText').textContent=a.regime==='TRENDING'?'Trend signals receive the most weight.':a.regime==='VOLATILE'?'ATR breakouts receive the most weight.':'Mean-reversion signals receive the most weight.';colorClass($('#heroSignal'),a.combined);$('#heroReason').textContent=`${a.regime} weighting applied across all three strategies.`;Object.values(a.strategies).forEach(v=>{const el=$(`.strategy-button[data-strategy="${v.id}"] em`);colorClass(el,v.signal)});$$('.strategy-button').forEach(b=>b.classList.toggle('active',b.dataset.strategy===active));$('#strategyName').textContent=s.name;$('#strategySubtitle').textContent=s.subtitle.toUpperCase();colorClass($('#currentSignal'),s.signal);$('#reasonText').textContent=s.reason;$('#metrics').innerHTML=[...s.metrics,['Confidence',confidence(s),'percent']].map(([n,v,t])=>`<div><span>${n}</span><b>${t==='money'?money(v):t==='multiple'?v.toFixed(2)+'×':t==='percent'?v+'%':v.toFixed(1)}</b></div>`).join('');renderPriceChart();renderBacktest();renderLog()}
function confidence(s){const base=s.signal==='BUY'||s.signal==='SELL'?72:s.signal==='WATCH'?58:62;return Math.min(92,base+(analysis.regime==='TRENDING'&&s.id==='trend'||analysis.regime==='VOLATILE'&&s.id==='atr'||analysis.regime==='RANGE-BOUND'&&s.id==='mean'?10:0))}
function chartOptions(){return{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{labels:{boxWidth:10,font:{size:10}}}},scales:{x:{grid:{display:false},ticks:{maxTicksLimit:6,font:{size:9}}},y:{grid:{color:'#e7e8e4'},ticks:{font:{size:9}}}}}}
function renderPriceChart(){const view=rows.slice(-130),offset=rows.length-view.length,ref=view.map((_,j)=>active==='trend'?sma(rows,20,offset+j):active==='mean'?analysis.s20:active==='atr'?analysis.resistance:null);priceChart?.destroy();priceChart=new Chart($('#priceChart'),{type:'line',data:{labels:view.map(x=>x.date),datasets:[{label:'Adjusted close',data:view.map(x=>x.close),borderColor:'#29bf7e',backgroundColor:'#29bf7e22',fill:true,pointRadius:0,borderWidth:2},{label:active==='trend'?'SMA 20':active==='mean'?'Bollinger midpoint':'Prior resistance',data:ref,borderColor:'#8491a1',pointRadius:0,borderDash:[5,5],borderWidth:1.5}]},options:chartOptions()})}
function renderBacktest(){const bt=backtest(rows,active);$('#strategyReturn').textContent=pct(bt.returnPct);$('#strategyReturn').className=bt.returnPct>=0?'buy':'sell';$('#holdReturn').textContent=pct(bt.holdPct);$('#trades').textContent=bt.trades;$('#winRate').textContent=`${bt.winRate.toFixed(0)}%`;$('#drawdown').textContent=`-${bt.maxDD.toFixed(1)}%`;$('#points').textContent=rows.length;equityChart?.destroy();equityChart=new Chart($('#equityChart'),{type:'line',data:{labels:bt.curve.map(x=>x.date),datasets:[{label:'Strategy',data:bt.curve.map(x=>x.strategy),borderColor:'#29bf7e',pointRadius:0,borderWidth:2.5},{label:'Buy & hold',data:bt.curve.map(x=>x.hold),borderColor:'#8390a1',pointRadius:0,borderWidth:2}]},options:{...chartOptions(),scales:{x:{ticks:{display:false},grid:{display:false}},y:{ticks:{color:'#a7b0bd',callback:v=>v.toFixed(2)+'×'},grid:{color:'#283649'}}},plugins:{legend:{labels:{color:'#b6c0cc',boxWidth:10}}}}})}
function logRows(){return Object.values(analysis.strategies).map(s=>({date:analysis.latest.date,symbol:ticker,strategy:s.name,regime:analysis.regime,signal:s.signal,reason:s.reason,source:`${source} DATA`}))}
function renderLog(){$('#logBody').innerHTML=logRows().map(x=>`<tr><td>${x.date}</td><td><b>${x.symbol}</b></td><td>${x.strategy}</td><td>${x.regime}</td><td><em class="${x.signal.toLowerCase()}">${x.signal}</em></td><td>${x.reason}</td></tr>`).join('')}
function downloadCsv(){const q=v=>`"${String(v).replaceAll('"','""')}"`,data=['date,symbol,strategy,regime,signal,reason,data_source',...logRows().map(x=>[x.date,x.symbol,x.strategy,x.regime,x.signal,x.reason,x.source].map(q).join(','))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:'text/csv'}));a.download=`${ticker}-decision-log.csv`;a.click();URL.revokeObjectURL(a.href)}
$('#searchForm').addEventListener('submit',e=>{e.preventDefault();scan($('#tickerInput').value)});$$('.strategy-button').forEach(b=>b.addEventListener('click',()=>{active=b.dataset.strategy;render()}));$$('[data-open]').forEach(b=>b.addEventListener('click',()=>{active=b.dataset.open;render();$('#scanner').scrollIntoView({behavior:'smooth'})}));$('#downloadCsv').addEventListener('click',downloadCsv);scan('AAPL');
